version: "3"

tasks:
  init:
    desc: Install all the rust tooling locally
    cmds:
      - rustup update
      - rustup install 1.80.1
      - rustup default 1.80.1
      - rustc --version
      - cargo --version
      - brew install lld
      - cargo install cargo-watch
      - cargo install cargo-llvm-cov --version 0.6.15
      - rustup component add clippy
      - rustup component add rustfmt
      - cargo install cargo-audit

  watch:
    desc: watch all files and run tests then app
    cmds:
      - cargo watch -x check -x test -x run

  test:
    desc: run tests
    cmds:
      - cargo test

  fmt:
    desc: format all files
    cmds:
      - cargo fmt

  audit:
    desc: audit for things
    cmds:
      - cargo audit
