version: "3"

tasks:
  init:
    desc: Install all the rust tooling locally
    cmds:
      - rustup update
      - rustup install 1.82.0
      - rustup default 1.82.0
      - rustc --version
      - cargo --version
      - brew install lld
      - cargo install cargo-watch --version 8.5.3
      - cargo install cargo-llvm-cov --version 0.6.15
      - rustup component add clippy
      - rustup component add rustfmt
      - cargo install cargo-audit --version 0.21.1
      - rustup toolchain install nightly
      - cargo +nightly install cargo-expand --version 1.0.114
      - cargo install sqlx-cli --version 0.6.3 --no-default-features --features rustls,postgres
      - cargo install cargo-udeps --version 0.1.29
      - cargo install bunyan --version 0.1.9

  pre-commit:
    desc: Run things that should be done pre-commiting
    deps:
      - fmt
      - tidy

  tidy:
    desc: clean up unused deps
    cmds:
      - cargo +nightly udeps --backend depinfo

  watch:
    desc: watch all files and run tests then app
    cmds:
      - cargo watch -x check -x test -x run

  test:
    desc: run tests
    cmds:
      - cargo test

  test-w-logs:
    desc: run tests with logs printing to stdout
    env:
      TEST_LOG: true
    cmds:
      - cargo test | bunyan

  fmt:
    desc: format all files
    cmds:
      - cargo fmt

  audit:
    desc: audit for things
    cmds:
      - cargo audit

  expand:
    desc: expand all the macros in our rust code
    cmds:
      - cargo +nightly expand

  db-up:
    desc: spin up the db container
    cmds:
      - ./scripts/init_db.sh

  db-migrate:
    desc: run the db migrations on the running database
    env:
      SKIP_DOCKER: true
    cmds:
      - ./scripts/init_db.sh

  db-down:
    desc: spin down the db container
    cmds:
      - docker stop postgres
      - docker rm postgres
